package main

import (
	"context" // Use "golang.org/x/net/context" for Golang version <= 1.6
	"flag"
	"fmt"
	"github.com/go-pg/pg"
	"net"
	"net/http"
	"time"

	"github.com/golang/glog"
	grpc_runtime "github.com/grpc-ecosystem/grpc-gateway/runtime"
	"google.golang.org/grpc"

	"github.com/xuanit/testing/todo/server/service/todo"
	repository "github.com/xuanit/testing/todo/server/repository"
	pb "github.com/xuanit/testing/todo/pb" // Update
)

var (
	// command-line options:
	// gRPC server endpoint
	grpcServerEndpoint = flag.String("grpc-server-endpoint",  "localhost:9090", "gRPC server endpoint")
)

func run() error {
	grpcAddress := "localhost:5001"
	httpAddress := "localhost:5002"


	// Connect to PostgresQL
	db := pg.Connect(&pg.Options{
		User:     "postgres",
		Password: "example",
		Database: "todo",
		Addr:     "localhost" + ":" + "5433",
		RetryStatementTimeout: true,
		MaxRetries:            4,
		MinRetryBackoff:       250 * time.Millisecond,
	})
	// Create Table from Todo struct generated by gRPC
	db.CreateTable(&pb.Todo{}, nil)


	s := grpc.NewServer()
	todoRep := repository.ToDoImpl{DB: db}
	pb.RegisterTodoServiceServer(s, todo.Service{ToDoRepo: todoRep})

	lis, err := net.Listen("tcp", grpcAddress)
	if err != nil {
		return fmt.Errorf("can not listen tcp grpcAddress %d: %v", grpcAddress, err)
	}
	go s.Serve(lis)

	conn, err := grpc.Dial(grpcAddress, grpc.WithInsecure())
	if err != nil {
		panic("Couldn't contact grpc server")
	}

	mux := grpc_runtime.NewServeMux()
	err = pb.RegisterTodoServiceHandler(context.Background(), mux, conn)
	if err != nil {
		panic("Cannot serve http api")
	}
	http.ListenAndServe(httpAddress, mux)
	return nil
}

func main() {
	flag.Parse()
	defer glog.Flush()

	if err := run(); err != nil {
		glog.Fatal(err)
	}
}